#! /usr/bin/env bash

set -e

HERE="$(readlink -f "$(dirname "$0")")"
BINARY_NAME=$(basename "$ARGV0")

export DEALERSCHOICE_DATADIR=$HERE/usr/share/dealers-choice

exec "$HERE/usr/bin/dealers-choice" "$@"

