/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dc_protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dc_protocol.pb-c.h"
void   card__init
                     (Card         *message)
{
  static const Card init_value = CARD__INIT;
  *message = init_value;
}
size_t card__get_packed_size
                     (const Card *message)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t card__pack
                     (const Card *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t card__pack_to_buffer
                     (const Card *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Card *
       card__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Card *)
     protobuf_c_message_unpack (&card__descriptor,
                                allocator, len, data);
}
void   card__free_unpacked
                     (Card *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &card__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hand__init
                     (Hand         *message)
{
  static const Hand init_value = HAND__INIT;
  *message = init_value;
}
size_t hand__get_packed_size
                     (const Hand *message)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hand__pack
                     (const Hand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hand__pack_to_buffer
                     (const Hand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hand *
       hand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hand *)
     protobuf_c_message_unpack (&hand__descriptor,
                                allocator, len, data);
}
void   hand__free_unpacked
                     (Hand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hand__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   player__init
                     (Player         *message)
{
  static const Player init_value = PLAYER__INIT;
  *message = init_value;
}
size_t player__get_packed_size
                     (const Player *message)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player__pack
                     (const Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player__pack_to_buffer
                     (const Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Player *
       player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Player *)
     protobuf_c_message_unpack (&player__descriptor,
                                allocator, len, data);
}
void   player__free_unpacked
                     (Player *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game_state__init
                     (GameState         *message)
{
  static const GameState init_value = GAME_STATE__INIT;
  *message = init_value;
}
size_t game_state__get_packed_size
                     (const GameState *message)
{
  assert(message->base.descriptor == &game_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game_state__pack
                     (const GameState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &game_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game_state__pack_to_buffer
                     (const GameState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &game_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GameState *
       game_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GameState *)
     protobuf_c_message_unpack (&game_state__descriptor,
                                allocator, len, data);
}
void   game_state__free_unpacked
                     (GameState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &game_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game_settings__init
                     (GameSettings         *message)
{
  static const GameSettings init_value = GAME_SETTINGS__INIT;
  *message = init_value;
}
size_t game_settings__get_packed_size
                     (const GameSettings *message)
{
  assert(message->base.descriptor == &game_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game_settings__pack
                     (const GameSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &game_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game_settings__pack_to_buffer
                     (const GameSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &game_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GameSettings *
       game_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GameSettings *)
     protobuf_c_message_unpack (&game_settings__descriptor,
                                allocator, len, data);
}
void   game_settings__free_unpacked
                     (GameSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &game_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ping_request__init
                     (PingRequest         *message)
{
  static const PingRequest init_value = PING_REQUEST__INIT;
  *message = init_value;
}
size_t ping_request__get_packed_size
                     (const PingRequest *message)
{
  assert(message->base.descriptor == &ping_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping_request__pack
                     (const PingRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping_request__pack_to_buffer
                     (const PingRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PingRequest *
       ping_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PingRequest *)
     protobuf_c_message_unpack (&ping_request__descriptor,
                                allocator, len, data);
}
void   ping_request__free_unpacked
                     (PingRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ping_response__init
                     (PingResponse         *message)
{
  static const PingResponse init_value = PING_RESPONSE__INIT;
  *message = init_value;
}
size_t ping_response__get_packed_size
                     (const PingResponse *message)
{
  assert(message->base.descriptor == &ping_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping_response__pack
                     (const PingResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping_response__pack_to_buffer
                     (const PingResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PingResponse *
       ping_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PingResponse *)
     protobuf_c_message_unpack (&ping_response__descriptor,
                                allocator, len, data);
}
void   ping_response__free_unpacked
                     (PingResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ping_entry__init
                     (PingEntry         *message)
{
  static const PingEntry init_value = PING_ENTRY__INIT;
  *message = init_value;
}
size_t ping_entry__get_packed_size
                     (const PingEntry *message)
{
  assert(message->base.descriptor == &ping_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping_entry__pack
                     (const PingEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping_entry__pack_to_buffer
                     (const PingEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PingEntry *
       ping_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PingEntry *)
     protobuf_c_message_unpack (&ping_entry__descriptor,
                                allocator, len, data);
}
void   ping_entry__free_unpacked
                     (PingEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ping_broadcast__init
                     (PingBroadcast         *message)
{
  static const PingBroadcast init_value = PING_BROADCAST__INIT;
  *message = init_value;
}
size_t ping_broadcast__get_packed_size
                     (const PingBroadcast *message)
{
  assert(message->base.descriptor == &ping_broadcast__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ping_broadcast__pack
                     (const PingBroadcast *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ping_broadcast__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ping_broadcast__pack_to_buffer
                     (const PingBroadcast *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ping_broadcast__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PingBroadcast *
       ping_broadcast__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PingBroadcast *)
     protobuf_c_message_unpack (&ping_broadcast__descriptor,
                                allocator, len, data);
}
void   ping_broadcast__free_unpacked
                     (PingBroadcast *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ping_broadcast__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor card__field_descriptors[2] =
{
  {
    "face_val",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Card, face_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Card, suit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned card__field_indices_by_name[] = {
  0,   /* field[0] = face_val */
  1,   /* field[1] = suit */
};
static const ProtobufCIntRange card__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor card__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Card",
  "Card",
  "Card",
  "",
  sizeof(Card),
  2,
  card__field_descriptors,
  card__field_indices_by_name,
  1,  card__number_ranges,
  (ProtobufCMessageInit) card__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hand__field_descriptors[1] =
{
  {
    "card",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Hand, n_card),
    offsetof(Hand, card),
    &card__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hand__field_indices_by_name[] = {
  0,   /* field[0] = card */
};
static const ProtobufCIntRange hand__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hand__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Hand",
  "Hand",
  "Hand",
  "",
  sizeof(Hand),
  1,
  hand__field_descriptors,
  hand__field_indices_by_name,
  1,  hand__number_ranges,
  (ProtobufCMessageInit) hand__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor player__field_descriptors[8] =
{
  {
    "nick",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Player, nick),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Player, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hand",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Player, hand),
    &hand__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coins",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Player, coins),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Player, in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "winner",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Player, winner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_connected",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Player, is_connected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_admin",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Player, is_admin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player__field_indices_by_name[] = {
  3,   /* field[3] = coins */
  2,   /* field[2] = hand */
  1,   /* field[1] = id */
  4,   /* field[4] = in */
  7,   /* field[7] = is_admin */
  6,   /* field[6] = is_connected */
  0,   /* field[0] = nick */
  5,   /* field[5] = winner */
};
static const ProtobufCIntRange player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Player",
  "Player",
  "Player",
  "",
  sizeof(Player),
  8,
  player__field_descriptors,
  player__field_indices_by_name,
  1,  player__number_ranges,
  (ProtobufCMessageInit) player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game_state__field_descriptors[9] =
{
  {
    "pot",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameState, pot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dealer_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GameState, dealer_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "at_menu",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GameState, at_menu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_count",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameState, player_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "raises_remaining",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameState, raises_remaining),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prev_bet_amount",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameState, prev_bet_amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "winner_declared",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GameState, winner_declared),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GameState, n_player),
    offsetof(GameState, player),
    &player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "round_opener_id",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GameState, round_opener_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game_state__field_indices_by_name[] = {
  2,   /* field[2] = at_menu */
  1,   /* field[1] = dealer_id */
  7,   /* field[7] = player */
  3,   /* field[3] = player_count */
  0,   /* field[0] = pot */
  5,   /* field[5] = prev_bet_amount */
  4,   /* field[4] = raises_remaining */
  8,   /* field[8] = round_opener_id */
  6,   /* field[6] = winner_declared */
};
static const ProtobufCIntRange game_state__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 7 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor game_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GameState",
  "GameState",
  "GameState",
  "",
  sizeof(GameState),
  9,
  game_state__field_descriptors,
  game_state__field_indices_by_name,
  2,  game_state__number_ranges,
  (ProtobufCMessageInit) game_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game_settings__field_descriptors[4] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GameSettings, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action_timeout_ms",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameSettings, action_timeout_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_of_game_timeout_ms",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameSettings, end_of_game_timeout_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bet_amounts",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(GameSettings, n_bet_amounts),
    offsetof(GameSettings, bet_amounts),
    NULL,
    NULL,
    PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game_settings__field_indices_by_name[] = {
  1,   /* field[1] = action_timeout_ms */
  3,   /* field[3] = bet_amounts */
  0,   /* field[0] = client_id */
  2,   /* field[2] = end_of_game_timeout_ms */
};
static const ProtobufCIntRange game_settings__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor game_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GameSettings",
  "GameSettings",
  "GameSettings",
  "",
  sizeof(GameSettings),
  4,
  game_settings__field_descriptors,
  game_settings__field_indices_by_name,
  2,  game_settings__number_ranges,
  (ProtobufCMessageInit) game_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ping_request__field_descriptors[1] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PingRequest, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ping_request__field_indices_by_name[] = {
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange ping_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ping_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PingRequest",
  "PingRequest",
  "PingRequest",
  "",
  sizeof(PingRequest),
  1,
  ping_request__field_descriptors,
  ping_request__field_indices_by_name,
  1,  ping_request__number_ranges,
  (ProtobufCMessageInit) ping_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ping_response__field_descriptors[1] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PingResponse, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ping_response__field_indices_by_name[] = {
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange ping_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ping_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PingResponse",
  "PingResponse",
  "PingResponse",
  "",
  sizeof(PingResponse),
  1,
  ping_response__field_descriptors,
  ping_response__field_indices_by_name,
  1,  ping_response__number_ranges,
  (ProtobufCMessageInit) ping_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ping_entry__field_descriptors[2] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PingEntry, player_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ping_ms",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PingEntry, ping_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ping_entry__field_indices_by_name[] = {
  1,   /* field[1] = ping_ms */
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange ping_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ping_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PingEntry",
  "PingEntry",
  "PingEntry",
  "",
  sizeof(PingEntry),
  2,
  ping_entry__field_descriptors,
  ping_entry__field_indices_by_name,
  1,  ping_entry__number_ranges,
  (ProtobufCMessageInit) ping_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ping_broadcast__field_descriptors[1] =
{
  {
    "entries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PingBroadcast, n_entries),
    offsetof(PingBroadcast, entries),
    &ping_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ping_broadcast__field_indices_by_name[] = {
  0,   /* field[0] = entries */
};
static const ProtobufCIntRange ping_broadcast__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ping_broadcast__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PingBroadcast",
  "PingBroadcast",
  "PingBroadcast",
  "",
  sizeof(PingBroadcast),
  1,
  ping_broadcast__field_descriptors,
  ping_broadcast__field_indices_by_name,
  1,  ping_broadcast__number_ranges,
  (ProtobufCMessageInit) ping_broadcast__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[3] =
{
  { "MSG_PING_REQUEST", "MESSAGE_TYPE__MSG_PING_REQUEST", 0 },
  { "MSG_PING_RESPONSE", "MESSAGE_TYPE__MSG_PING_RESPONSE", 1 },
  { "MSG_PING_BROADCAST", "MESSAGE_TYPE__MSG_PING_BROADCAST", 2 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[3] =
{
  { "MSG_PING_BROADCAST", 2 },
  { "MSG_PING_REQUEST", 0 },
  { "MSG_PING_RESPONSE", 1 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  3,
  message_type__enum_values_by_number,
  3,
  message_type__enum_values_by_name,
  1,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
