/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: dc_registry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "dc_registry.pb-c.h"
void   server_announce__init
                     (ServerAnnounce         *message)
{
  static const ServerAnnounce init_value = SERVER_ANNOUNCE__INIT;
  *message = init_value;
}
size_t server_announce__get_packed_size
                     (const ServerAnnounce *message)
{
  assert(message->base.descriptor == &server_announce__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_announce__pack
                     (const ServerAnnounce *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_announce__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_announce__pack_to_buffer
                     (const ServerAnnounce *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_announce__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerAnnounce *
       server_announce__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerAnnounce *)
     protobuf_c_message_unpack (&server_announce__descriptor,
                                allocator, len, data);
}
void   server_announce__free_unpacked
                     (ServerAnnounce *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_announce__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_entry__init
                     (ServerEntry         *message)
{
  static const ServerEntry init_value = SERVER_ENTRY__INIT;
  *message = init_value;
}
size_t server_entry__get_packed_size
                     (const ServerEntry *message)
{
  assert(message->base.descriptor == &server_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_entry__pack
                     (const ServerEntry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_entry__pack_to_buffer
                     (const ServerEntry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerEntry *
       server_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerEntry *)
     protobuf_c_message_unpack (&server_entry__descriptor,
                                allocator, len, data);
}
void   server_entry__free_unpacked
                     (ServerEntry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_list_request__init
                     (ServerListRequest         *message)
{
  static const ServerListRequest init_value = SERVER_LIST_REQUEST__INIT;
  *message = init_value;
}
size_t server_list_request__get_packed_size
                     (const ServerListRequest *message)
{
  assert(message->base.descriptor == &server_list_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_list_request__pack
                     (const ServerListRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_list_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_list_request__pack_to_buffer
                     (const ServerListRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_list_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerListRequest *
       server_list_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerListRequest *)
     protobuf_c_message_unpack (&server_list_request__descriptor,
                                allocator, len, data);
}
void   server_list_request__free_unpacked
                     (ServerListRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_list_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   server_list__init
                     (ServerList         *message)
{
  static const ServerList init_value = SERVER_LIST__INIT;
  *message = init_value;
}
size_t server_list__get_packed_size
                     (const ServerList *message)
{
  assert(message->base.descriptor == &server_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t server_list__pack
                     (const ServerList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &server_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t server_list__pack_to_buffer
                     (const ServerList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &server_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ServerList *
       server_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ServerList *)
     protobuf_c_message_unpack (&server_list__descriptor,
                                allocator, len, data);
}
void   server_list__free_unpacked
                     (ServerList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &server_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor server_announce__field_descriptors[8] =
{
  {
    "registry_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ServerAnnounce, registry_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerAnnounce, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ServerAnnounce, tcp_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_count",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ServerAnnounce, player_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_players",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ServerAnnounce, max_players),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password_protected",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ServerAnnounce, password_protected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_progress",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ServerAnnounce, in_progress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ServerAnnounce, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_announce__field_indices_by_name[] = {
  6,   /* field[6] = in_progress */
  4,   /* field[4] = max_players */
  1,   /* field[1] = name */
  5,   /* field[5] = password_protected */
  3,   /* field[3] = player_count */
  0,   /* field[0] = registry_version */
  7,   /* field[7] = start_time */
  2,   /* field[2] = tcp_port */
};
static const ProtobufCIntRange server_announce__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor server_announce__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerAnnounce",
  "ServerAnnounce",
  "ServerAnnounce",
  "",
  sizeof(ServerAnnounce),
  8,
  server_announce__field_descriptors,
  server_announce__field_indices_by_name,
  1,  server_announce__number_ranges,
  (ProtobufCMessageInit) server_announce__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_entry__field_descriptors[8] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerEntry, ip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ServerEntry, tcp_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ServerEntry, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_count",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ServerEntry, player_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_players",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ServerEntry, max_players),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password_protected",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ServerEntry, password_protected),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_progress",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ServerEntry, in_progress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_time",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ServerEntry, start_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_entry__field_indices_by_name[] = {
  6,   /* field[6] = in_progress */
  0,   /* field[0] = ip */
  4,   /* field[4] = max_players */
  2,   /* field[2] = name */
  5,   /* field[5] = password_protected */
  3,   /* field[3] = player_count */
  7,   /* field[7] = start_time */
  1,   /* field[1] = tcp_port */
};
static const ProtobufCIntRange server_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor server_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerEntry",
  "ServerEntry",
  "ServerEntry",
  "",
  sizeof(ServerEntry),
  8,
  server_entry__field_descriptors,
  server_entry__field_indices_by_name,
  1,  server_entry__number_ranges,
  (ProtobufCMessageInit) server_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_list_request__field_descriptors[1] =
{
  {
    "registry_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ServerListRequest, registry_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_list_request__field_indices_by_name[] = {
  0,   /* field[0] = registry_version */
};
static const ProtobufCIntRange server_list_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor server_list_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerListRequest",
  "ServerListRequest",
  "ServerListRequest",
  "",
  sizeof(ServerListRequest),
  1,
  server_list_request__field_descriptors,
  server_list_request__field_indices_by_name,
  1,  server_list_request__number_ranges,
  (ProtobufCMessageInit) server_list_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor server_list__field_descriptors[1] =
{
  {
    "servers",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ServerList, n_servers),
    offsetof(ServerList, servers),
    &server_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned server_list__field_indices_by_name[] = {
  0,   /* field[0] = servers */
};
static const ProtobufCIntRange server_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor server_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ServerList",
  "ServerList",
  "ServerList",
  "",
  sizeof(ServerList),
  1,
  server_list__field_descriptors,
  server_list__field_indices_by_name,
  1,  server_list__number_ranges,
  (ProtobufCMessageInit) server_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
