/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: netpoker.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "netpoker.pb-c.h"
void   card__init
                     (Card         *message)
{
  static const Card init_value = CARD__INIT;
  *message = init_value;
}
size_t card__get_packed_size
                     (const Card *message)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t card__pack
                     (const Card *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t card__pack_to_buffer
                     (const Card *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &card__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Card *
       card__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Card *)
     protobuf_c_message_unpack (&card__descriptor,
                                allocator, len, data);
}
void   card__free_unpacked
                     (Card *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &card__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hand__init
                     (Hand         *message)
{
  static const Hand init_value = HAND__INIT;
  *message = init_value;
}
size_t hand__get_packed_size
                     (const Hand *message)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hand__pack
                     (const Hand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hand__pack_to_buffer
                     (const Hand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hand__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hand *
       hand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hand *)
     protobuf_c_message_unpack (&hand__descriptor,
                                allocator, len, data);
}
void   hand__free_unpacked
                     (Hand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hand__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   player__init
                     (Player         *message)
{
  static const Player init_value = PLAYER__INIT;
  *message = init_value;
}
size_t player__get_packed_size
                     (const Player *message)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player__pack
                     (const Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player__pack_to_buffer
                     (const Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Player *
       player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Player *)
     protobuf_c_message_unpack (&player__descriptor,
                                allocator, len, data);
}
void   player__free_unpacked
                     (Player *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game_state__init
                     (GameState         *message)
{
  static const GameState init_value = GAME_STATE__INIT;
  *message = init_value;
}
size_t game_state__get_packed_size
                     (const GameState *message)
{
  assert(message->base.descriptor == &game_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game_state__pack
                     (const GameState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &game_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game_state__pack_to_buffer
                     (const GameState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &game_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GameState *
       game_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GameState *)
     protobuf_c_message_unpack (&game_state__descriptor,
                                allocator, len, data);
}
void   game_state__free_unpacked
                     (GameState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &game_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game_settings__init
                     (GameSettings         *message)
{
  static const GameSettings init_value = GAME_SETTINGS__INIT;
  *message = init_value;
}
size_t game_settings__get_packed_size
                     (const GameSettings *message)
{
  assert(message->base.descriptor == &game_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game_settings__pack
                     (const GameSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &game_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game_settings__pack_to_buffer
                     (const GameSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &game_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GameSettings *
       game_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GameSettings *)
     protobuf_c_message_unpack (&game_settings__descriptor,
                                allocator, len, data);
}
void   game_settings__free_unpacked
                     (GameSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &game_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor card__field_descriptors[2] =
{
  {
    "face_val",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Card, face_val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suit",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Card, suit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned card__field_indices_by_name[] = {
  0,   /* field[0] = face_val */
  1,   /* field[1] = suit */
};
static const ProtobufCIntRange card__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor card__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Card",
  "Card",
  "Card",
  "",
  sizeof(Card),
  2,
  card__field_descriptors,
  card__field_indices_by_name,
  1,  card__number_ranges,
  (ProtobufCMessageInit) card__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hand__field_descriptors[1] =
{
  {
    "card",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Hand, n_card),
    offsetof(Hand, card),
    &card__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hand__field_indices_by_name[] = {
  0,   /* field[0] = card */
};
static const ProtobufCIntRange hand__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hand__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Hand",
  "Hand",
  "Hand",
  "",
  sizeof(Hand),
  1,
  hand__field_descriptors,
  hand__field_indices_by_name,
  1,  hand__number_ranges,
  (ProtobufCMessageInit) hand__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor player__field_descriptors[8] =
{
  {
    "nick",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Player, nick),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Player, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hand",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Player, hand),
    &hand__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coins",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Player, coins),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Player, in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_paid",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Player, total_paid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "winner",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Player, winner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "has_checked",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Player, has_checked),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player__field_indices_by_name[] = {
  3,   /* field[3] = coins */
  2,   /* field[2] = hand */
  7,   /* field[7] = has_checked */
  1,   /* field[1] = id */
  4,   /* field[4] = in */
  0,   /* field[0] = nick */
  5,   /* field[5] = total_paid */
  6,   /* field[6] = winner */
};
static const ProtobufCIntRange player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Player",
  "Player",
  "Player",
  "",
  sizeof(Player),
  8,
  player__field_descriptors,
  player__field_indices_by_name,
  1,  player__number_ranges,
  (ProtobufCMessageInit) player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game_state__field_descriptors[8] =
{
  {
    "pot",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameState, pot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dealer_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GameState, dealer_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "turn_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GameState, turn_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "at_menu",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GameState, at_menu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_count",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameState, player_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_bets_plus_raises",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameState, total_bets_plus_raises),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "winner_declared",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GameState, winner_declared),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(GameState, n_player),
    offsetof(GameState, player),
    &player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game_state__field_indices_by_name[] = {
  3,   /* field[3] = at_menu */
  1,   /* field[1] = dealer_id */
  7,   /* field[7] = player */
  4,   /* field[4] = player_count */
  0,   /* field[0] = pot */
  5,   /* field[5] = total_bets_plus_raises */
  2,   /* field[2] = turn_id */
  6,   /* field[6] = winner_declared */
};
static const ProtobufCIntRange game_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor game_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GameState",
  "GameState",
  "GameState",
  "",
  sizeof(GameState),
  8,
  game_state__field_descriptors,
  game_state__field_indices_by_name,
  1,  game_state__number_ranges,
  (ProtobufCMessageInit) game_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game_settings__field_descriptors[3] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(GameSettings, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action_timeout_ms",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameSettings, action_timeout_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_of_game_timeout_ms",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GameSettings, end_of_game_timeout_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game_settings__field_indices_by_name[] = {
  1,   /* field[1] = action_timeout_ms */
  0,   /* field[0] = client_id */
  2,   /* field[2] = end_of_game_timeout_ms */
};
static const ProtobufCIntRange game_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor game_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GameSettings",
  "GameSettings",
  "GameSettings",
  "",
  sizeof(GameSettings),
  3,
  game_settings__field_descriptors,
  game_settings__field_indices_by_name,
  1,  game_settings__number_ranges,
  (ProtobufCMessageInit) game_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
