/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: netpoker.proto */

#ifndef PROTOBUF_C_netpoker_2eproto__INCLUDED
#define PROTOBUF_C_netpoker_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Card Card;
typedef struct Hand Hand;
typedef struct Player Player;
typedef struct GameState GameState;


/* --- enums --- */


/* --- messages --- */

struct  Card
{
  ProtobufCMessage base;
  int32_t face_val;
  int32_t suit;
};
#define CARD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&card__descriptor) \
, 0, 0 }


struct  Hand
{
  ProtobufCMessage base;
  size_t n_card;
  Card **card;
};
#define HAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hand__descriptor) \
, 0,NULL }


struct  Player
{
  ProtobufCMessage base;
  char *nick;
  int32_t id;
  Hand *hand;
  int32_t coins;
  protobuf_c_boolean in;
  uint32_t total_paid;
  protobuf_c_boolean winner;
  protobuf_c_boolean has_checked;
};
#define PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&player__descriptor) \
, (char *)protobuf_c_empty_string, 0, NULL, 0, 0, 0, 0, 0 }


struct  GameState
{
  ProtobufCMessage base;
  uint32_t pot;
  int32_t dealer_id;
  int32_t turn_id;
  protobuf_c_boolean at_menu;
  uint32_t player_count;
  uint32_t total_bets_plus_raises;
  protobuf_c_boolean winner_declared;
  int32_t action_time_out_ms;
  int32_t end_of_round_time_out_ms;
  size_t n_player;
  Player **player;
};
#define GAME_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game_state__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL }


/* Card methods */
void   card__init
                     (Card         *message);
size_t card__get_packed_size
                     (const Card   *message);
size_t card__pack
                     (const Card   *message,
                      uint8_t             *out);
size_t card__pack_to_buffer
                     (const Card   *message,
                      ProtobufCBuffer     *buffer);
Card *
       card__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   card__free_unpacked
                     (Card *message,
                      ProtobufCAllocator *allocator);
/* Hand methods */
void   hand__init
                     (Hand         *message);
size_t hand__get_packed_size
                     (const Hand   *message);
size_t hand__pack
                     (const Hand   *message,
                      uint8_t             *out);
size_t hand__pack_to_buffer
                     (const Hand   *message,
                      ProtobufCBuffer     *buffer);
Hand *
       hand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hand__free_unpacked
                     (Hand *message,
                      ProtobufCAllocator *allocator);
/* Player methods */
void   player__init
                     (Player         *message);
size_t player__get_packed_size
                     (const Player   *message);
size_t player__pack
                     (const Player   *message,
                      uint8_t             *out);
size_t player__pack_to_buffer
                     (const Player   *message,
                      ProtobufCBuffer     *buffer);
Player *
       player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   player__free_unpacked
                     (Player *message,
                      ProtobufCAllocator *allocator);
/* GameState methods */
void   game_state__init
                     (GameState         *message);
size_t game_state__get_packed_size
                     (const GameState   *message);
size_t game_state__pack
                     (const GameState   *message,
                      uint8_t             *out);
size_t game_state__pack_to_buffer
                     (const GameState   *message,
                      ProtobufCBuffer     *buffer);
GameState *
       game_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game_state__free_unpacked
                     (GameState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Card_Closure)
                 (const Card *message,
                  void *closure_data);
typedef void (*Hand_Closure)
                 (const Hand *message,
                  void *closure_data);
typedef void (*Player_Closure)
                 (const Player *message,
                  void *closure_data);
typedef void (*GameState_Closure)
                 (const GameState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor card__descriptor;
extern const ProtobufCMessageDescriptor hand__descriptor;
extern const ProtobufCMessageDescriptor player__descriptor;
extern const ProtobufCMessageDescriptor game_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_netpoker_2eproto__INCLUDED */
