services:
  docker-dealers-choice-server:
    image: ghcr.io/dealer-s-choice/dealers_choice:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.alpine
    command: ["dealers-choice", "--server"]
    ports:
      - "22777:22777"
    restart: unless-stopped
