FROM opensuse/tumbleweed

RUN zypper --non-interactive refresh && \
    zypper --non-interactive update && \
    zypper --non-interactive install \
    gettext \
    gcc \
    git \
    SDL2-devel \
    SDL2_image-devel \
    SDL2_ttf-devel \
    libcanfigger0-devel \
    libsodium-devel \
    meson \
    ninja \
    protobuf-c-devel && \
    zypper clean

RUN useradd -U builder && \
    passwd -d builder

CMD ["/bin/bash", "-l"]
