/*
 gen_keys_doc.c
 https://github.com/Dealer-s-Choice/dealers_choice

 Written by Claude (Anthropic, Opus 4.8) at Andy's direction.

 MIT License

 Copyright (c) 2026 Andy Alt

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

*/

/*
 * Generates docs/keys.md from the shared hotkey tables in
 * src/ui/hotkey_table.{c,h}.  The same tables drive the in-game F1 overlay, so
 * the docs and the running game can never disagree about the key list.
 *
 * Meson runs this at build/dist time; see the gen-keys-doc custom_target.  The
 * tool writes to a path given on argv[1] (the build-dir copy) and also to argv[2]
 * if a second path is given (used by the regenerate-keys-doc run_target to
 * refresh the in-tree docs/keys.md).  With no arguments it writes to stdout.
 *
 * Why a C tool and not a shell/python script?  The source of truth is C data
 * (g_hotkey_defs[] / g_fixed_keys[] in hotkey_table.c), because the running game
 * needs it as C at runtime anyway.  This tool *links* hotkey_table.c and reads
 * those structs directly, so it consumes the exact data the game compiles -- no
 * text-parsing of the C source, so the docs can never drift from the code.  A
 * script would have to regex the array initialisers, which breaks the moment the
 * table is reformatted or gains a field (e.g. when FixedKeyDef_t.in_game_only was
 * added, this tool needed zero changes).  In meson it is `native: true` so a
 * cross-build produces a generator that runs on the build host, not the target.
 */

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "hotkey_table.h"

/* Strip the "hotkey_" prefix and capitalise the first letter, so "hotkey_check"
 * becomes "Check" for the action column. */
static void action_label(const char *config_key, char *out, size_t out_sz) {
  const char *p = config_key;
  if (strncmp(p, "hotkey_", 7) == 0)
    p += 7;
  snprintf(out, out_sz, "%s", p);
  if (out[0])
    out[0] = (char)toupper((unsigned char)out[0]);
  for (char *c = out; *c; c++)
    if (*c == '_')
      *c = ' '; /* "hand_rank" -> "Hand rank" */
}

static void write_doc(FILE *fp) {
  fputs("<!-- Generated by tools/gen_keys_doc.c from src/ui/hotkey_table.c.\n"
        "     Do not edit by hand; edit the table and rebuild. -->\n\n",
        fp);
  fputs("# Game-play keys\n\n", fp);
  fputs("This page lists the keys used during a game. Press F1 while playing to\n"
        "see the same list on screen.\n\n",
        fp);

  fputs("## Action keys (you can change these)\n\n", fp);
  fputs("These keys are set in your `player.conf` file. The defaults are shown\n"
        "below. You can also change them from the Settings screen.\n\n",
        fp);
  fputs("| Action | Default key | What it does |\n", fp);
  fputs("|---|---|---|\n", fp);
  for (size_t i = 0; i < g_hotkey_def_count; i++) {
    char label[32];
    action_label(g_hotkey_defs[i].config_key, label, sizeof(label));
    fprintf(fp, "| %s | `%s` | %s |\n", label, g_hotkey_defs[i].default_key,
            g_hotkey_defs[i].description);
  }

  fputs("\nTo change a key, edit its line in `player.conf`, for example:\n\n", fp);
  fputs("```\n", fp);
  for (size_t i = 0; i < g_hotkey_def_count; i++)
    fprintf(fp, "%s = %s\n", g_hotkey_defs[i].config_key, g_hotkey_defs[i].default_key);
  fputs("```\n\n", fp);
  fputs("A key value can be a single letter or an SDL key name (for example\n"
        "`Space`, `Up`, or `Home`). Each action needs its own key.\n\n",
        fp);

  fputs("## Fixed keys (you cannot change these)\n\n", fp);
  fputs("These keys always do the same thing. The hotkey editor will not let you\n"
        "use them for an action.\n\n",
        fp);
  fputs("| Key | What it does |\n", fp);
  fputs("|---|---|\n", fp);
  for (size_t i = 0; i < g_fixed_key_count; i++)
    fprintf(fp, "| `%s` | %s |\n", g_fixed_keys[i].keys, g_fixed_keys[i].description);
  fputc('\n', fp);
}

int main(int argc, char **argv) {
  if (argc < 2) {
    write_doc(stdout);
    return 0;
  }

  for (int i = 1; i < argc; i++) {
    FILE *fp = fopen(argv[i], "w");
    if (!fp) {
      fprintf(stderr, "gen_keys_doc: cannot open '%s' for writing\n", argv[i]);
      return 1;
    }
    write_doc(fp);
    fclose(fp);
  }
  return 0;
}
