name: Linux
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ trunk ]
    paths: &shared_paths
      - '**'
      - '!**.yml'
      - '!**.md'
      - '**/linux.yml'

  pull_request:
    branches: [ trunk ]
    paths: *shared_paths


jobs:
  Ubuntu:
    strategy:
      matrix:
        name: [default]
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
        cc:
          - gcc
          - clang
        include:
          - name: dist-test
            os: ubuntu-22.04
            cc: gcc
          - name: Arch Linux
            os: ubuntu-latest
            cc: gcc
            container: ghcr.io/dealer-s-choice/build_env:build-env-arch

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v6
    - name: Install Dependencies
      if: ${{ matrix.container == null }}
      run: .github/scripts/install_ubuntu_deps.sh

    - name: Meson setup
      run: CFLAGS="-Werror" meson setup _build -Dsodium=enabled

    - name: Build
      run: meson compile -C _build

    - name: Test
      run: meson test --no-stdsplit -v -C _build

    - name: Dist test
      if: ${{ contains(matrix.name, 'dist-test') }}
      run: meson dist -C _build

    - name: Install test
      run: meson install --destdir=install_test -C _build
