name: MacOS
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Linux"]
    types: [completed]

jobs:
  MacOS:
    if: github.event.workflow_run.conclusion == 'success'
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - macos-14
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Install Dependencies
      run: |
        brew update
        brew install \
          canfigger \
          gettext \
          meson \
          miniaudio \
          protobuf-c \
          sdl2 \
          sdl2_image \
          sdl2_net \
          sdl2_ttf \
          libsodium

    - name: Meson setup
      run: |
        GETTEXT_PREFIX=$(brew --prefix gettext)
        echo $GETTEXT_PREFIX
        # PKG_CONFIG_PATH="$GETTEXT_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
        CFLAGS="-Werror" meson setup _build -Dsodium=enabled

    - name: Build
      run: meson compile -v -C _build

    - name: Test
      run: meson test -v -C _build
