name: MacOS
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ trunk ]
    paths: &shared_paths
    - '**'
    - '!**.yml'
    - '!**.md'
    - '!docker/Dockerfile-build-env_**'
    - '**/macos.yml'

  pull_request:
    branches: [ trunk ]
    paths: *shared_paths

jobs:
  MacOS:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - macOS-15-arm64
          - macOS-26
    runs-on: ${{ matrix.os }}
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
    - uses: actions/checkout@v7
    - name: Cache Homebrew packages
      uses: actions/cache@v5
      with:
        path: ~/Library/Caches/Homebrew
        key: ${{ runner.os }}-${{ matrix.os }}-brew-${{ hashFiles('.github/workflows/macos.yml') }}
        restore-keys: ${{ runner.os }}-${{ matrix.os }}-brew-
    - name: Install Dependencies
      run: |
        brew install \
          canfigger \
          gettext \
          meson \
          protobuf-c \
          sdl2 \
          sdl2_image \
          sdl2_ttf \
          libsodium

    - name: Meson setup
      run: |
        GETTEXT_PREFIX=$(brew --prefix gettext)
        echo $GETTEXT_PREFIX
        # PKG_CONFIG_PATH="$GETTEXT_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
        CFLAGS="-Werror" meson setup _build

    - name: Build
      run: meson compile -v -C _build

    - name: Test
      run: meson test -v -C _build
