name: MacOS
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ trunk ]
    paths: &shared_paths
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/macos.yml'

  pull_request:
    branches: [ trunk ]
    paths: *shared_paths

jobs:
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        brew update
        brew install \
          cmake \
          gettext \
          meson \
          protobuf-c \
          sdl2 \
          sdl2_image \
          sdl2_net \
          sdl2_ttf

    - name: Meson setup
      run: |
        GETTEXT_PREFIX=$(brew --prefix gettext)
        echo $GETTEXT_PREFIX
        # PKG_CONFIG_PATH="$GETTEXT_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
        CFLAGS="-Werror" meson setup _build

    - name: Build
      run: meson compile -C _build

    - name: Test
      run: meson test -v -C _build
