name: Windows
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ trunk ]
    paths: &shared_paths
    - '**'
    - '!**.yml'
    - '!**.md'
    - '**/windows.yml'

  pull_request:
    branches: [ trunk ]
    paths: *shared_paths

jobs:
  MSYS2:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: ['UCRT64', 'CLANG64']
    steps:
    - uses: actions/checkout@v6
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.platform}}
        install: >-
          git
        pacboy: >-
          cc:p
          cmake:p
          gettext:p
          meson:p
          ninja:p
          pkgconf:p
          protobuf-c:p
          SDL2:p
          SDL2_image:p
          SDL2_net:p
          SDL2_ttf:p
        update: true

    - name: Meson setup
      shell: msys2 {0}
      run: |
        CFLAGS="-Werror" meson setup _build -Db_sanitize=none

    - name: Build
      shell: msys2 {0}
      run: |
        meson compile -C _build

    - name: Test
      shell: msys2 {0}
      continue-on-error: true
      run: |
        meson test --no-stdsplit -v -C _build
